[tools]
bat = "latest"
btop = "latest"
chezmoi = "latest"
lsd = "latest"
mdbook = "latest"
node = "latest"
"pipx:salt" = "latest"
python = "latest"
rust = "latest"
starship = "latest"
"ubi:ifd3f/caligula" = "latest"
yq = "latest"
